  name: deploy

  on:
    push:
      branches:
        - dev

  jobs:
    cd:
      runs-on: ${{ matrix.os }}

      strategy:
        matrix:
          os: [ubuntu-latest]
          node: [14]

      steps:
        - name: Checkout
          uses: actions/checkout@master

        - name: Setup node env
          uses: actions/setup-node@v2.1.2
          with:
            node-version: ${{ matrix.node }}

        - name: Install dependencies
          run: npm i

        - name: Build module
          run: npm run build

        - name: Clean useless files
          run: rm -rf ./src && rm -rf ./node_modules

        - name: Deploy
          run: npm publish
          env:
            NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}